--
-- 转存表中的数据 `{tablename}`
--

INSERT INTO `{tablename}` VALUES(36, 2, '与总理同框：里加16+1诞生了两张“全家福”', '25', '', '简体中文', '共享版', '["WinXp","Win7","Win8","Linux","Mac"]', '', '中国-中东欧合作机制似乎与水结缘。“16+1”领导人会晤，从最初的多瑙河畔到去年的太湖之滨，如今又来到波罗的海。似乎巧合、更像隐喻的是：中国哲学讲究“水到渠成”，16+1合作，尤其是中东欧16国对推动基础设施和...', 5, 1, 'admin', 9, '/index.php?c=show&id=36', 0, 0, '192.168.0.9', 1478484450, 1478485038, 0, 0, 0);
INSERT INTO `{tablename}` VALUES(37, 2, '一图感知习近平制度治党有多拼', '24', '', '简体中文', '共享版', '["WinXp","Win7"]', '', '一图感知习近平制度治党有多拼', 1, 1, 'admin', 9, '/index.php?c=show&id=37', 0, 0, '192.168.0.9', 1478484505, 1478485025, 0, 0, 0);
INSERT INTO `{tablename}` VALUES(38, 2, '中国和欧洲的农民起义有何区别', '23', '', '简体中文', '共享版', '["Win7","Win8"]', '', '中国和欧洲的农民起义有何区别1、古典文献中有“起义”一词，但无“农民起义”一词笔者使用“诸子百家中国哲学书电子化计划”检索，查询“农民起义”词条，所得结果为0；查询“起义”词条，则结果极多。如《水经注》...', 0, 1, 'admin', 9, '/index.php?c=show&id=38', 0, 0, '192.168.0.9', 1478484540, 1478485012, 0, 0, 0);
INSERT INTO `{tablename}` VALUES(39, 2, '中国和欧洲的农民起义有何区别', '22', '', '简体中文', '共享版', '["Win7","Win8"]', '', '中国和欧洲的农民起义有何区别1、古典文献中有“起义”一词，但无“农民起义”一词笔者使用“诸子百家中国哲学书电子化计划”检索，查询“农民起义”词条，所得结果为0；查询“起义”词条，则结果极多。如《水经注》...', 0, 1, 'admin', 9, '/index.php?c=show&id=39', 0, 0, '192.168.0.9', 1478484540, 1478484997, 0, 0, 0);
INSERT INTO `{tablename}` VALUES(40, 2, '中央派组督察15省份换届风气 严禁拉票贿选', '21', '', '简体中文', '共享版', '["Linux","Mac"]', '', '可通过电话网络短信信访举报据报道，中组部有关负责同志在动员部署时强调，督察工作要坚持从严从实，突出问题导向，对责任落实、教育宣传、监督察处、制度执行、“凡提四必”等方面情况进行“五个必查”，努力做到对...', 0, 1, 'admin', 9, '/index.php?c=show&id=40', 0, 0, '192.168.0.9', 1478484587, 1478484976, 0, 0, 0);
INSERT INTO `{tablename}` VALUES(41, 2, '全球最富的20个国家 无中国', '20', '', '简体中文', '共享版', '["Win8"]', '', '全球最富的20个国家 无中国英国智库列格坦研究所(Legatum Institute)发布了2016年“全球繁荣指数”，为这个世界上最繁荣的国家进行了排名。财富是判断一个国家繁荣程度的重要因素，但是在进行国家排名时列格坦研究所...', 0, 1, 'admin', 9, '/index.php?c=show&id=41', 0, 0, '192.168.0.9', 1478484605, 1478484951, 0, 0, 0);
INSERT INTO `{tablename}` VALUES(42, 2, '中联办主任：绝不容许“港独”分子就任议员', '19', '', '简体中文', '共享版', '["Win7"]', '', '中联办主任：绝不容许“港独”分子就任议员', 1, 1, 'admin', 9, '/index.php?c=show&id=42', 0, 0, '192.168.0.9', 1478484718, 1478484938, 0, 0, 0);
INSERT INTO `{tablename}` VALUES(43, 2, '除了崔顺实，韩亲信干政事件还涉及哪些核心人物', '18', '', '简体中文', '共享版', '["Win7","Win8"]', '', '除了崔顺实，韩亲信干政事件还涉及哪些核心人物', 3, 1, 'admin', 9, '/index.php?c=show&id=43', 0, 0, '192.168.0.9', 1478484734, 1478484808, 0, 0, 0);

-- --------------------------------------------------------
--
-- 转存表中的数据 `{tablename}_comment_index`
--

INSERT INTO `{tablename}_comment_index` VALUES(1, 43, 0, 0, 0, '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', 0);
INSERT INTO `{tablename}_comment_index` VALUES(2, 37, 0, 0, 0, '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', 0);
INSERT INTO `{tablename}_comment_index` VALUES(3, 42, 0, 0, 0, '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', 0);
INSERT INTO `{tablename}_comment_index` VALUES(4, 36, 0, 0, 0, '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', 0);

-- --------------------------------------------------------
--
-- 转存表中的数据 `{tablename}_data_0`
--

INSERT INTO `{tablename}_data_0` VALUES(36, 1, 2, '', '', '', '', '<p><span style="font: 16px/28px &quot;Microsoft Yahei&quot;, Helvetica, sans-serif; color: rgb(0, 0, 0); text-transform: none; text-indent: 32px; letter-spacing: normal; word-spacing: 0px; float: none; display: inline !important; white-space: normal; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px;">中国-中东欧合作机制似乎与水结缘。“16+1”领导人会晤，从最初的多瑙河畔到去年的太湖之滨，如今又来到波罗的海。似乎巧合、更像隐喻的是：中国哲学讲究“水到渠成”，16+1合作，尤其是中东欧16国对推动基础设施和互联互通巨大的需求，与中国在装备制造性价比最优的产能以及推动工业化进程的经验对接，从而使得相互间开展国际产能合作变得顺理成章、水到渠成。</span></p>');
INSERT INTO `{tablename}_data_0` VALUES(37, 1, 2, '', '', '', '', '<h1 style="margin: 0px 0px 15px; padding: 0px; color: rgb(0, 0, 0); text-transform: none; text-indent: 0px; letter-spacing: normal; font-family: &quot;Microsoft Yahei&quot;, Helvetica, sans-serif; font-size: 26px; font-style: normal; font-variant: normal; font-weight: normal; word-spacing: 0px; white-space: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px;">一图感知习近平制度治党有多拼</h1><p>&nbsp;</p>');
INSERT INTO `{tablename}_data_0` VALUES(38, 1, 2, '', '', '', '', '<h1 style="font: bold 32px/45px 微软雅黑, 黑体; margin: 0px; padding: 15px 0px 0px; height: 45px; color: rgb(51, 51, 51); text-transform: none; text-indent: 0px; letter-spacing: normal; overflow: hidden; word-spacing: 0px; white-space: normal; font-size-adjust: none; font-stretch: normal; background-color: rgb(246, 246, 246); -webkit-text-stroke-width: 0px;">中国和欧洲的农民起义有何区别</h1><p style="font: 16px/28px &quot;simsun Arial&quot;; margin: 0px; padding: 0px 0px 20px; color: rgb(68, 68, 68); text-transform: none; text-indent: 2em; letter-spacing: normal; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px;" data-page-model="text"><strong>1、古典文献中有“起义”一词，但无“农民起义”一词</strong></p><p style="font: 16px/28px &quot;simsun Arial&quot;; margin: 0px; padding: 0px 0px 20px; color: rgb(68, 68, 68); text-transform: none; text-indent: 2em; letter-spacing: normal; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px;" data-page-model="text">笔者使用“诸子百家中国哲学书电子化计划”检索，查询“农民起义”词条，所得结果为0；查询“起义”词条，则结果极多。如《水经注》“汝水”条下，有“汝南太守周矜起义于悬瓠者是矣”之句。《三国志·袁绍传》裴注中，有“袁绍起义，卑辞厚币以招致（田）丰”之句。《通典》中有“桓玄篡晋，宋武帝起义讨之”、“大唐高祖起义至京师”、“大唐起义太原”等句。《三国演义》中，“高祖斩白蛇而起义”、“斩蛇起义”等句，出现频率也很高。</p><p style="font: 16px/28px &quot;simsun Arial&quot;; margin: 0px; padding: 0px 0px 20px; color: rgb(68, 68, 68); text-transform: none; text-indent: 2em; letter-spacing: normal; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px;" data-page-model="text"><strong>2、民国报刊杂志及学术界很少使用“农民起义”，该词直到50年代才出现井喷</strong></p><p style="font: 16px/28px &quot;simsun Arial&quot;; margin: 0px; padding: 0px 0px 20px; color: rgb(68, 68, 68); text-transform: none; text-indent: 2em; letter-spacing: normal; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px;" data-page-model="text">“农民起义”一词最早见于何人作品，很难搞明白。可以肯定的是，要到50年代，该词才在报刊杂志和书籍中大量出现（40年代后期的《新华日报》，已较频繁使用该词）。笔者于《民国38年前重要剪报资料库》中检索“农民起义”，仅得1项结果（检索“起义”有130项结果）。孙中山生平文章，经常使用“起义”一词，但笔者于“国父全集全文检索系统”中检索“农民起义”，则结果为0（检索“起义”有481笔资料）。</p><p>&nbsp;</p>');
INSERT INTO `{tablename}_data_0` VALUES(39, 1, 2, '', '', '', '', '<h1 style="font: bold 32px/45px 微软雅黑, 黑体; margin: 0px; padding: 15px 0px 0px; height: 45px; color: rgb(51, 51, 51); text-transform: none; text-indent: 0px; letter-spacing: normal; overflow: hidden; word-spacing: 0px; white-space: normal; font-size-adjust: none; font-stretch: normal; background-color: rgb(246, 246, 246); -webkit-text-stroke-width: 0px;">中国和欧洲的农民起义有何区别</h1><p style="font: 16px/28px &quot;simsun Arial&quot;; margin: 0px; padding: 0px 0px 20px; color: rgb(68, 68, 68); text-transform: none; text-indent: 2em; letter-spacing: normal; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px;" data-page-model="text"><strong>1、古典文献中有“起义”一词，但无“农民起义”一词</strong></p><p style="font: 16px/28px &quot;simsun Arial&quot;; margin: 0px; padding: 0px 0px 20px; color: rgb(68, 68, 68); text-transform: none; text-indent: 2em; letter-spacing: normal; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px;" data-page-model="text">笔者使用“诸子百家中国哲学书电子化计划”检索，查询“农民起义”词条，所得结果为0；查询“起义”词条，则结果极多。如《水经注》“汝水”条下，有“汝南太守周矜起义于悬瓠者是矣”之句。《三国志·袁绍传》裴注中，有“袁绍起义，卑辞厚币以招致（田）丰”之句。《通典》中有“桓玄篡晋，宋武帝起义讨之”、“大唐高祖起义至京师”、“大唐起义太原”等句。《三国演义》中，“高祖斩白蛇而起义”、“斩蛇起义”等句，出现频率也很高。</p><p style="font: 16px/28px &quot;simsun Arial&quot;; margin: 0px; padding: 0px 0px 20px; color: rgb(68, 68, 68); text-transform: none; text-indent: 2em; letter-spacing: normal; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px;" data-page-model="text"><strong>2、民国报刊杂志及学术界很少使用“农民起义”，该词直到50年代才出现井喷</strong></p><p style="font: 16px/28px &quot;simsun Arial&quot;; margin: 0px; padding: 0px 0px 20px; color: rgb(68, 68, 68); text-transform: none; text-indent: 2em; letter-spacing: normal; word-spacing: 0px; white-space: normal; -ms-word-wrap: break-word; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px;" data-page-model="text">“农民起义”一词最早见于何人作品，很难搞明白。可以肯定的是，要到50年代，该词才在报刊杂志和书籍中大量出现（40年代后期的《新华日报》，已较频繁使用该词）。笔者于《民国38年前重要剪报资料库》中检索“农民起义”，仅得1项结果（检索“起义”有130项结果）。孙中山生平文章，经常使用“起义”一词，但笔者于“国父全集全文检索系统”中检索“农民起义”，则结果为0（检索“起义”有481笔资料）。</p><p>&nbsp;</p>');
INSERT INTO `{tablename}_data_0` VALUES(40, 1, 2, '', '', '', '', '<p style="font: 16px/28px &quot;Microsoft Yahei&quot;, Helvetica, sans-serif; margin: 0px 0px 28px; padding: 0px; color: rgb(0, 0, 0); text-transform: none; text-indent: 2em; letter-spacing: normal; word-spacing: 0px; white-space: normal; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px;"><strong>可通过电话网络短信信访举报</strong></p><p style="font: 16px/28px &quot;Microsoft Yahei&quot;, Helvetica, sans-serif; margin: 0px 0px 28px; padding: 0px; color: rgb(0, 0, 0); text-transform: none; text-indent: 2em; letter-spacing: normal; word-spacing: 0px; white-space: normal; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px;">据报道，中组部有关负责同志在动员部署时强调，督察工作要坚持从严从实，突出问题导向，对责任落实、教育宣传、监督察处、制度执行、“凡提四必”等方面情况进行“五个必查”，努力做到对换届进展情况、换届风气状况、突出问题矛盾、干部群众反映、潜在风险隐患等“五个搞清楚”，切实把督察工作沉下去，把真实情况摸清楚，进一步增强督察督导实效。</p><p style="font: 16px/28px &quot;Microsoft Yahei&quot;, Helvetica, sans-serif; margin: 0px 0px 28px; padding: 0px; color: rgb(0, 0, 0); text-transform: none; text-indent: 2em; letter-spacing: normal; word-spacing: 0px; white-space: normal; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px;">同时，中组部和15个被督察省（区、市）党委组织部门“12380”电话、网络、短信和信访“四位一体”举报平台，将认真受理违反换届纪律问题的举报。</p><p>&nbsp;</p>');
INSERT INTO `{tablename}_data_0` VALUES(41, 1, 2, '', '', '', '', '<h1 style="margin: 0px; padding: 0px; border: 0px currentColor; border-image: none; color: rgb(227, 184, 118); text-transform: none; line-height: normal; text-indent: 0px; letter-spacing: normal; font-family: &quot;Microsoft YaHei&quot;; font-size: 40px; font-style: normal; font-variant: normal; word-spacing: 0px; vertical-align: baseline; white-space: normal; background-color: rgb(244, 244, 244); -webkit-text-stroke-width: 0px;">全球最富的20个国家 无中国</h1><p style="margin: 24px 0px; padding: 0px; border: 0px currentColor; border-image: none; color: rgb(0, 0, 0); text-transform: none; text-indent: 0px; letter-spacing: normal; word-spacing: 0px; vertical-align: baseline; white-space: normal; -ms-word-wrap: break-word; background-color: rgb(244, 244, 244); -webkit-text-stroke-width: 0px;" data-page-model="text">英国智库列格坦研究所(Legatum Institute)发布了2016年“全球繁荣指数”，为这个世界上最繁荣的国家进行了排名。</p><p style="margin: 24px 0px; padding: 0px; border: 0px currentColor; border-image: none; color: rgb(0, 0, 0); text-transform: none; text-indent: 0px; letter-spacing: normal; word-spacing: 0px; vertical-align: baseline; white-space: normal; -ms-word-wrap: break-word; background-color: rgb(244, 244, 244); -webkit-text-stroke-width: 0px;" data-page-model="text">财富是判断一个国家繁荣程度的重要因素，但是在进行国家排名时列格坦研究所考虑的因素远不止这个。统计数据显示，该研究所在进行排名时参考了104种可变因素，其中包括人均国内生产总值和全职工作人数等传统指标，还包括安全互联网服务器的数量，以及人们每日的起色如何等更加有趣的因素。</p><p>&nbsp;</p>');
INSERT INTO `{tablename}_data_0` VALUES(42, 1, 2, '', '', '', '', '<h1 style="margin: 0px 0px 15px; padding: 0px; color: rgb(0, 0, 0); text-transform: none; text-indent: 0px; letter-spacing: normal; font-family: &quot;Microsoft Yahei&quot;, Helvetica, sans-serif; font-size: 26px; font-style: normal; font-variant: normal; font-weight: normal; word-spacing: 0px; white-space: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px;">中联办主任：绝不容许“港独”分子就任议员</h1><p>&nbsp;</p>');
INSERT INTO `{tablename}_data_0` VALUES(43, 1, 2, '', '', '', '', '<h1 style="margin: 0px 0px 15px; padding: 0px; color: rgb(0, 0, 0); text-transform: none; text-indent: 0px; letter-spacing: normal; font-family: &quot;Microsoft Yahei&quot;, Helvetica, sans-serif; font-size: 26px; font-style: normal; font-variant: normal; font-weight: normal; word-spacing: 0px; white-space: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px;">除了崔顺实，韩亲信干政事件还涉及哪些核心人物</h1><p>&nbsp;</p>');

-- --------------------------------------------------------
--
-- 转存表中的数据 `{tablename}_hits`
--

INSERT INTO `{tablename}_hits` VALUES(43, 3, 3, 4, 4, 1);
INSERT INTO `{tablename}_hits` VALUES(37, 1, 1, 2, 2, 1);
INSERT INTO `{tablename}_hits` VALUES(42, 1, 1, 2, 2, 1);
INSERT INTO `{tablename}_hits` VALUES(36, 5, 1, 6, 6, 1);

-- --------------------------------------------------------
--
-- 转存表中的数据 `{tablename}_index`
--

INSERT INTO `{tablename}_index` VALUES(36, 1, 2, 9, 1478484450);
INSERT INTO `{tablename}_index` VALUES(37, 1, 2, 9, 1478484505);
INSERT INTO `{tablename}_index` VALUES(38, 1, 2, 9, 1478484540);
INSERT INTO `{tablename}_index` VALUES(39, 1, 2, 9, 1478484540);
INSERT INTO `{tablename}_index` VALUES(40, 1, 2, 9, 1478484587);
INSERT INTO `{tablename}_index` VALUES(41, 1, 2, 9, 1478484605);
INSERT INTO `{tablename}_index` VALUES(42, 1, 2, 9, 1478484718);
INSERT INTO `{tablename}_index` VALUES(43, 1, 2, 9, 1478484734);

-- --------------------------------------------------------